name: "Batcontrol"
description: "Controls the charging of the battery"
version: "0.0.17"
slug: "batcontrol"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  timezone: Europe/Berlin #your time zone. not optional.
  loglevel: debug
  battery_control:
    min_price_difference: 0.05 # minimum price difference in Euro to justify charging your battery
    always_allow_discharge_limit: 0.90 # 0.00 to 1.00 above this SOC limit using energy from the battery is always allowed
    max_charging_from_grid_limit: 0.90 # 0.00 to 1.00 charging from the grid is only allowed until this SOC limit
  inverter:
    type: fronius_gen24 #currently only fronius_gen24 supported
    address: 192.168.0.XX # the local IP of your inverter. needs to be reachable from the machine that runs batcontrol
    user: customer #customer or technician lowercase only!!
    password: YOUR-PASSWORD #
  utility:
    type: tibber
    apikey: Zz-YOURAPIKEYYOURAPIKEYXXXXX
  pvinstallations:
    - name: Haus #name
      lat: 48.4334480
      lon: 8.7654968
      declination: 32 #inclination toward horizon 0..90 0=flat 90=vertical (e.g. wallmounted)
      azimuth: -90 # -90:East, 0:South, 90:West -180..180
      kWp: 15.695 # power in kWp
  consumption_forecast:
    annual_consumption: 4500 # total consumption in kWh p.a. the load profile
    load_profile: load_profile.csv #name of the load profile file within the config folder
schema:
  timezone: str #your time zone. not optional.
  loglevel: list(debug|info|warning|error)
  battery_control:
    min_price_difference: float(0,) # minimum price difference in Euro to justify charging your battery
    always_allow_discharge_limit: float(0,1) # 0.00 to 1.00 above this SOC limit using energy from the battery is always allowed
    max_charging_from_grid_limit: float(0,1) # 0.00 to 1.00 charging from the grid is only allowed until this SOC limit
  inverter:
    type: list(fronius_gen24) #currently only fronius_gen24 supported
    address: str # the local IP of your inverter. needs to be reachable from the machine that runs batcontrol
    user: list(customer|technician) #customer or technician lowercase only!!
    password: password
  utility:
    type: list(tibber)
    apikey: password
  pvinstallations:
    - name: str #name
      lat: float(,90)
      lon: float(,90)
      declination: float(0,90) #inclination toward horizon 0..90 0=flat 90=vertical (e.g. wallmounted)
      azimuth: float(,180) # -90:East, 0:South, 90:West -180..180
      kWp: float(0,) # power in kWp
  consumption_forecast:
    annual_consumption: float(0,)? # total consumption in kWh p.a. the load profile
    load_profile: str #name of the load profile file within the config folder
